services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-xdoc
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge